---
language: go

notifications:
  email: false

matrix:
  include:
    - go: 1.10.x
      script: go test -v ./...
    - go: 1.11.x
      env: GO111MODULE=on
      install: go mod download
      script: go test -v ./...
    - go: 1.12.x
      env: GO111MODULE=on
      install: go mod download
      script: go test -v ./...
    - go: tip
      env: GO111MODULE=on
      install: go mod download
      script: go test -v ./...
