---
name: Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go_version: [1.11.x, 1.12.x]

    name: Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - uses: actions/checkout@v1

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Run tests
        run: go test -mod readonly -race
